// Code generated by MockGen. DO NOT EDIT.
// Source: search/core/ports.go
//
// Generated by this command:
//
//	mockgen -source=search/core/ports.go -destination=search/core/mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	core "yadro.com/course/search/core"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// ISearch mocks base method.
func (m *MockSearcher) ISearch(ctx context.Context, limit int, phrase string) ([]core.PbComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISearch", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.PbComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISearch indicates an expected call of ISearch.
func (mr *MockSearcherMockRecorder) ISearch(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISearch", reflect.TypeOf((*MockSearcher)(nil).ISearch), ctx, limit, phrase)
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, limit int, phrase string) ([]core.PbComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.PbComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, limit, phrase)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// GetAllComics mocks base method.
func (m *MockDB) GetAllComics(ctx context.Context) ([]core.Comics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllComics", ctx)
	ret0, _ := ret[0].([]core.Comics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllComics indicates an expected call of GetAllComics.
func (mr *MockDBMockRecorder) GetAllComics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllComics", reflect.TypeOf((*MockDB)(nil).GetAllComics), ctx)
}

// SearchComics mocks base method.
func (m *MockDB) SearchComics(ctx context.Context, limit int, phrase []string) ([]core.PbComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchComics", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.PbComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchComics indicates an expected call of SearchComics.
func (mr *MockDBMockRecorder) SearchComics(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchComics", reflect.TypeOf((*MockDB)(nil).SearchComics), ctx, limit, phrase)
}

// MockWords is a mock of Words interface.
type MockWords struct {
	ctrl     *gomock.Controller
	recorder *MockWordsMockRecorder
	isgomock struct{}
}

// MockWordsMockRecorder is the mock recorder for MockWords.
type MockWordsMockRecorder struct {
	mock *MockWords
}

// NewMockWords creates a new mock instance.
func NewMockWords(ctrl *gomock.Controller) *MockWords {
	mock := &MockWords{ctrl: ctrl}
	mock.recorder = &MockWordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWords) EXPECT() *MockWordsMockRecorder {
	return m.recorder
}

// Norm mocks base method.
func (m *MockWords) Norm(ctx context.Context, phrase string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Norm", ctx, phrase)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Norm indicates an expected call of Norm.
func (mr *MockWordsMockRecorder) Norm(ctx, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Norm", reflect.TypeOf((*MockWords)(nil).Norm), ctx, phrase)
}

// MockIndexer is a mock of Indexer interface.
type MockIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerMockRecorder
	isgomock struct{}
}

// MockIndexerMockRecorder is the mock recorder for MockIndexer.
type MockIndexerMockRecorder struct {
	mock *MockIndexer
}

// NewMockIndexer creates a new mock instance.
func NewMockIndexer(ctrl *gomock.Controller) *MockIndexer {
	mock := &MockIndexer{ctrl: ctrl}
	mock.recorder = &MockIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexer) EXPECT() *MockIndexerMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockIndexer) Build(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Build indicates an expected call of Build.
func (mr *MockIndexerMockRecorder) Build(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockIndexer)(nil).Build), ctx)
}

// ISearchComics mocks base method.
func (m *MockIndexer) ISearchComics(ctx context.Context, limit int, phrase []string) ([]core.PbComic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ISearchComics", ctx, limit, phrase)
	ret0, _ := ret[0].([]core.PbComic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ISearchComics indicates an expected call of ISearchComics.
func (mr *MockIndexerMockRecorder) ISearchComics(ctx, limit, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ISearchComics", reflect.TypeOf((*MockIndexer)(nil).ISearchComics), ctx, limit, phrase)
}
